name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        ./test.ps1 -noReport
      shell: pwsh
    - name: Codecov
      uses: codecov/codecov-action@v3.1.4
      with:
        # User defined upload name. Visible in Codecov UI
        name: Nut.Results
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        files: ./nut.results.coverage.xml,./nut.results.fluentassertions.coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
