name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test Nut.Results
      run: dotnet test --no-restore --verbosity normal ./test/Nut.Results.Test/Nut.Results.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../../nut.results.coverage.xml /p:Exclude="[Nut.Results.FluentAssertions*]*" /p:ExcludeByAttribute=CompilerGenerated
    - name: Test Nut.Results.FluentAssertions
      run: dotnet test --no-restore --verbosity normal ./test/Nut.Results.FluentAssertions.Test/Nut.Results.FluentAssertions.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../../nut.results.fluentassertions.coverage.xml /p:Include="[Nut.Results.FluentAssertions*]*" /p:ExcludeByAttribute=CompilerGenerated
    - name: Codecov
      uses: codecov/codecov-action@v1.0.14
      with:
        # User defined upload name. Visible in Codecov UI
        name: Nut.Results
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        files: ./nut.results.coverage.xml,./nut.results.fluentassertions.coverage.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
